# GPU 지원을 위해 기본 이미지를 nvidia/cuda 기반으로 설정
FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04

# Python 및 필수 패키지 설치
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir torch transformers fastapi pydantic uvicorn

RUN pip3 install --no-cache-dir accelerate vllm

RUN pip3 install --no-cache-dir Flask

# 작업 디렉토리 설정
WORKDIR /app

VOLUME ["/app/huggingface_cache"]

ENV HF_HOME=/app/huggingface_cache

COPY ./llm_inference_server.py /app/llm_inference_server.py
