FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir torch transformers fastapi pydantic uvicorn

RUN pip3 install --no-cache-dir flask qdrant-client sentence-transformers datasets

WORKDIR /app

COPY ./embedding_server_async.py /app/embedding_server_async.py
